
all:

rand:
	gcc -o rand rand.c

square_constant_size:
	gcc -o square_constant_size square_constant_size.c

square_linear_size:
	gcc -o square_linear_size square_linear_size.c

trig_sz_const_free_fwd:
	gcc -o trig_sz_const_free_fwd trig_sz_const_free_fwd.c

trig_sz_const_free_rev:
	gcc -o trig_sz_const_free_rev trig_sz_const_free_rev.c

trig_sz_linea_free_fwd:
	gcc -o trig_sz_linea_free_fwd trig_sz_linea_free_fwd.c

trig_sz_linea_free_rev:
	gcc -o trig_sz_linea_free_rev trig_sz_linea_free_rev.c

.PHONY: clean
clean:
	rm -f square_constant_size square_linear_size trig_sz_const_free_fwd trig_sz_const_free_rev trig_sz_linea_free_fwd trig_sz_linea_free_rev